import type { WorkplaceLearnLesson, WorkplaceLearnVocabulary } from './types.ts'

/** Original hypothetical teaching fixture; not a claim about every Japanese workplace. */
export const sampleWorkplaceLearnItem: WorkplaceLearnLesson = {
  schemaVersion: 1,
  kind: 'lesson',
  id: 'workplace-learn-sample-status-update',
  slug: 'sample-status-update-with-next-step',
  title: '報告時に事実と次の対応を短く伝える',
  titleLanguage: 'ja',
  lead: '進捗に遅れが出たときは、状況・影響・次の対応を分けて共有します。',
  leadLanguage: 'ja',
  category: 'workplace-communication',
  tags: ['progress-reporting', 'next-action'],
  access: 'free',
  situation: '架空的公司專案中，資料確認比預期多花半天，原訂今天寄出的草案可能延後。',
  meaningInContextZhTW: '此處先交代目前確認的事實，再補上可能影響與下次更新時間，讓主管或同事能判斷是否需要調整安排。',
  learningObjective: '遇到進度延遲時，能用日文報告事實、預期影響與下一次更新時間。',
  capabilityDomain: 'hou-ren-sou',
  skill: 'Reporting a schedule delay with a next update',
  coreJudgment: '先判斷延遲是否會影響他人的工作，再明確說出已知事實與仍待確認的部分。',
  whatToDo: '儘早告知相關人員目前進度，說明可能影響，提出暫定的下一步與更新時間；若影響尚未確定，要清楚標示為預估。',
  whatToSayJapanese: '確認作業に想定より時間がかかっており、本日中に予定していた資料の共有が難しい見込みです。影響範囲を確認し、15時までに改めて状況をご報告します。',
  whyItWorksZhTW: '先交代原因並標示判斷仍有不確定性，最後用明確時間承諾再次更新。',
  practiceTypes: ['rewrite'],
  transferTakeaway: '報告進度變化時，讓對方知道目前事實、可能影響，以及你何時會帶著新資訊再聯絡。',
  examples: [
    {
      context: '向負責排定後續確認時間的同事報告',
      japanese: '先方への確認がまだ終わっていません。回答を受け取り次第、今日の16時までに共有します。',
      explanationZhTW: '說明尚未完成的確認，並把下次分享時間與觸發條件說清楚。',
    },
  ],
  cautionZhTW: '這是架空情境的表達示例，不代表所有公司都使用相同語氣或回報流程。請依團隊約定、緊急程度及對方職責調整細節；不要把尚未確認的影響說成確定結果。',
  relationshipContext: '對主管或會受延遲影響的同事，宜及早共享可確認的資訊；團隊既定的報告方式與語氣優先。',
  relatedVocabularyIds: ['workplace-learn-sample-mikomi'],
  relatedLinks: [],
  sampleLabel: 'non-proprietary-teaching-sample',
}

/** Original hypothetical vocabulary fixture linked to the Free lesson above. */
export const sampleWorkplaceVocabularyItem: WorkplaceLearnVocabulary = {
  schemaVersion: 1,
  kind: 'vocabulary',
  id: 'workplace-learn-sample-mikomi',
  slug: 'sample-mikomi-estimate',
  title: '見込み',
  titleLanguage: 'ja',
  lead: '根據目前資訊判斷可能出現的結果或進度。',
  leadLanguage: 'zh-TW',
  category: 'workplace-vocabulary',
  tags: ['progress-reporting', 'estimates'],
  access: 'free',
  term: '見込み',
  reading: 'みこみ',
  meaningZhTW: '預估、預期；根據目前掌握的資訊推測可能結果。',
  workplaceNuanceZhTW: '用來表達目前判斷的可能結果，語氣保留不確定性。可搭配表示預估結果的句型，說明預計會發生什麼事，但不等於保證。',
  usageContext: '報告進度或排程時，依目前狀況告知預估完成時間或可能影響。',
  example: {
    context: '告知資料分享時間可能延後',
    japanese: '資料の確認に時間がかかっており、共有は明日になる見込みです。',
    explanationZhTW: '這種說法表示依目前狀況預估明天才能分享，仍需視確認進度而定。',
  },
  cautionZhTW: '若結果已經確定，直接報告事實會更清楚；若使用預估，應補充何時會再次確認或更新，避免對方把可能性當成承諾。這是架空教學例句，請依實際情境調整。',
  register: '禮貌、適用於一般工作進度報告；可用於對主管或同事說明。',
  relationshipContext: '面向會受時程影響的人時，除了預估，也要說明下一次確認時間。',
  relatedTermIds: [],
  relatedLinks: [{ kind: 'learn', label: sampleWorkplaceLearnItem.title, labelLanguage: 'ja', targetId: sampleWorkplaceLearnItem.id }],
  sampleLabel: 'non-proprietary-teaching-sample',
}
