import type { WorkplaceLearnLesson, WorkplaceLearnVocabulary } from './types.ts'

/** Original hypothetical Japanese fixture. It remains a draft pending independent content review. */
export const sampleWorkplaceLearnItem: WorkplaceLearnLesson = {
  schemaVersion: 2,
  kind: 'lesson',
  id: 'workplace-learn-sample-status-update',
  slug: 'sample-status-update-with-next-step',
  title: '報告時に事実と次の対応を短く伝える',
  titleLanguage: 'ja',
  lead: '進捗に遅れが出たときは、状況・影響・次の対応を分けて共有します。',
  leadLanguage: 'ja',
  category: 'workplace-communication',
  tags: ['progress-reporting', 'next-action'],
  access: 'free',
  situation: '架空のプロジェクトで、資料の確認に予定より半日かかり、今日送る予定の草案が遅れる可能性が出ました。',
  meaningInContextJa: 'まず確認できている事実を伝え、次に考えられる影響と次回の報告時刻を示します。相手が予定を調整する必要があるか判断しやすくなります。',
  learningObjective: '進捗に遅れが出たとき、事実・想定される影響・次回の報告時刻を日本語で伝えられるようになります。',
  capabilityDomain: 'hou-ren-sou',
  skill: '次回の報告時刻を添えて進捗の遅れを伝える',
  coreJudgment: '遅れが相手の仕事に影響するかを考え、分かっている事実と確認中の点を分けて伝えます。',
  whatToDo: '関係者に早めに進捗を知らせ、考えられる影響と次の対応を伝えます。影響がまだ分からない場合は、確認中であることと次に報告する時刻を明示します。',
  whatToSayJapanese: '確認作業に想定より時間がかかっており、資料を本日中に共有できない可能性があります。影響範囲を確認し、15時までに改めて状況をご報告します。',
  whyItWorksJa: '確認できている状況とまだ分からない点を分け、次に報告する時刻を示すことで、相手が見通しを立てやすくなります。',
  practiceTypes: ['rewrite'],
  transferTakeaway: '進捗の変化を伝えるときは、分かっている事実、考えられる影響、新しい情報を伝える時刻を順に示します。',
  examples: [
    {
      context: '次の確認時刻を決める同僚に状況を共有する',
      japanese: '先方への確認がまだ終わっていません。回答を受け取り次第、共有します。回答がまだ届いていなくても、今日の16時までに確認状況を共有します。',
      explanationJa: '確認が終わっていない事実を伝え、回答の共有と、回答の有無にかかわらず行う状況報告を分けています。',
    },
  ],
  cautionJa: 'これは架空の場面を使った表現例です。会社ごとの慣習や報告手順を示すものではありません。チームの取り決め、緊急度、相手の役割に合わせて調整し、未確認の影響を確定事項のように伝えないでください。',
  relationshipContext: '上司や遅れの影響を受ける同僚には、確認できた情報を早めに共有します。チームで決めた報告方法や語調があれば、そちらを優先してください。',
  relatedVocabularyIds: ['workplace-learn-sample-mikomi'],
  relatedLinks: [],
  sampleLabel: 'non-proprietary-teaching-sample',
}

/** Original hypothetical Japanese vocabulary fixture; draft pending independent content review. */
export const sampleWorkplaceVocabularyItem: WorkplaceLearnVocabulary = {
  schemaVersion: 2,
  kind: 'vocabulary',
  id: 'workplace-learn-sample-mikomi',
  slug: 'sample-mikomi-estimate',
  title: '見込み',
  titleLanguage: 'ja',
  lead: '現時点の情報から予測される結果や進捗を表します。',
  leadLanguage: 'ja',
  category: 'workplace-vocabulary',
  tags: ['progress-reporting', 'estimates'],
  access: 'free',
  term: '見込み',
  reading: 'みこみ',
  meaningJa: '現時点の情報をもとに予測した結果。',
  workplaceNuanceJa: '確定していない予測を表します。予測の根拠や、次に確認・更新する時刻も添えると、相手が見通しを立てやすくなります。',
  usageContext: '進捗や日程を報告するとき、現在の状況から予測した完了時刻や影響を伝えます。',
  example: {
    context: '資料の共有が遅れる可能性を伝える',
    japanese: '資料の確認に時間がかかっており、共有は明日になる見込みです。本日15時までに、確認の進み具合を改めてご報告します。',
    explanationJa: '現時点では明日の共有を予測していますが、確定した予定とは区別しています。また、確認の進み具合を本日15時までに報告すると伝えています。',
  },
  cautionJa: 'すでに結果が確定している場合は、事実をそのまま伝える方が明確です。予測を伝えるときは次に確認・更新する時刻も示し、可能性が確約と受け取られないようにしてください。',
  register: '丁寧な業務連絡で使えます。上司や同僚への進捗共有にも適しています。',
  relationshipContext: '日程の影響を受ける相手には、予測だけでなく次に確認する時刻も伝えます。',
  relatedTermIds: [],
  relatedLinks: [{ kind: 'learn', label: sampleWorkplaceLearnItem.title, labelLanguage: 'ja', targetId: sampleWorkplaceLearnItem.id }],
  sampleLabel: 'non-proprietary-teaching-sample',
}
