import { describe, expect, it } from 'vitest';
import {
  applyEcpayEncodeSubstitutions,
  canonicalCheckMacString,
  ecpayCheckMac,
  ecpayUrlEncode,
  sha256Hex,
  verifyCheckMac,
} from './checkmac';

/** Test-only ECPay stage credentials (decision-record §16). */
const HASH_KEY = '5294y06JbISpM5x9';
const HASH_IV = 'v77hoKGq4kWxNNIS';

/**
 * Independent known-answer vectors generated by a reference implementation of
 * §5 (sort → join → HashKey/HashIV → urlencode+substitutions → lowercase →
 * SHA-256 → uppercase) — NOT by the module under test.
 */
const V1_PARAMS: Record<string, string> = {
  MerchantID: '2000132',
  MerchantTradeNo: 'BJH202608160001',
  MerchantTradeDate: '2026/08/16 10:30:00',
  PaymentType: 'aio',
  TotalAmount: '790',
  TradeDesc: 'Business Japanese Hub book purchase',
  ItemName: 'Keigo Essentials',
  ReturnURL: 'https://example.com/functions/v1/ecpay-callback',
  ChoosePayment: 'Credit',
  EncryptType: '1',
  NeedExtraPaidInfo: 'N',
  Language: 'JPN',
};
const V1_EXPECTED = '778C97A638B6550E20270197B1D0BF3F07B38873E3FA83B9464C69B4DF5B9EA0';

/** Contains reserved URL characters and a CheckMacValue that must be excluded. */
const V2_PARAMS: Record<string, string> = {
  MerchantID: '2000132',
  MerchantTradeNo: 'BJH-2026_08.16!001*',
  TotalAmount: '79000',
  ItemName: 'Keigo & Business (100%) [Re:零]',
  ReturnURL: 'https://example.com/cb?a=1&b=2',
  CheckMacValue: 'FORGED_VALUE_SHOULD_BE_EXCLUDED',
};
const V2_EXPECTED = '6E80056DB97EFE1F724A5E02F4016CF0CABC7567E6EDDE826E274C1FC7EE895F';

/** Callback-shape params (allowlisted evidence fields). */
const V3_PARAMS: Record<string, string> = {
  MerchantID: '2000132',
  MerchantTradeNo: 'BJHQ202608160003',
  TradeNo: '2026081612345678901',
  TradeAmt: '790',
  PaymentDate: '2026/08/16 10:31:00',
  PaymentType: 'Credit_CreditCard',
  RtnCode: '1',
  RtnMsg: 'Succeeded',
  SimulatePaid: '0',
};
const V3_EXPECTED = '83A595D7F1B9BA9789848327E4FFDD1ED6D00889A2F3971F4F3199396137BD86';

/** QueryTradeInfo-shape params. */
const V4_PARAMS: Record<string, string> = {
  MerchantID: '2000132',
  MerchantTradeNo: 'BJH202608160001',
  TimeStamp: '1755320400',
};
const V4_EXPECTED = '045553C490F82007F9FB59257E47C2A86F53A60BEA98DAF79386DB17EAC8ABD4';

describe('ecpayCheckMac (§5 canonicalization)', () => {
  it('matches the independent known-answer vector V1', async () => {
    await expect(ecpayCheckMac(V1_PARAMS, HASH_KEY, HASH_IV)).resolves.toBe(V1_EXPECTED);
  });

  it('matches V2 and correctly excludes CheckMacValue', async () => {
    await expect(ecpayCheckMac(V2_PARAMS, HASH_KEY, HASH_IV)).resolves.toBe(V2_EXPECTED);
    // Adding a CheckMacValue must not change the digest.
    const withMac = { ...V1_PARAMS, CheckMacValue: 'ANYTHING' };
    await expect(ecpayCheckMac(withMac, HASH_KEY, HASH_IV)).resolves.toBe(V1_EXPECTED);
  });

  it('matches the callback-shape vector V3', async () => {
    await expect(ecpayCheckMac(V3_PARAMS, HASH_KEY, HASH_IV)).resolves.toBe(V3_EXPECTED);
  });

  it('matches the query-shape vector V4', async () => {
    await expect(ecpayCheckMac(V4_PARAMS, HASH_KEY, HASH_IV)).resolves.toBe(V4_EXPECTED);
  });

  it('is independent of key insertion order (keys are sorted)', async () => {
    const reversed: Record<string, string> = {};
    for (const key of Object.keys(V1_PARAMS).reverse()) {
      reversed[key] = V1_PARAMS[key];
    }
    await expect(ecpayCheckMac(reversed, HASH_KEY, HASH_IV)).resolves.toBe(V1_EXPECTED);
  });

  it('returns a 64-char uppercase hex digest', async () => {
    const digest = await ecpayCheckMac(V1_PARAMS, HASH_KEY, HASH_IV);
    expect(digest).toMatch(/^[0-9A-F]{64}$/);
  });
});

describe('ecpayUrlEncode (§5 encoding)', () => {
  it('passes the safe characters through unchanged', () => {
    expect(ecpayUrlEncode('a-b_c.d!e*f(g)h')).toBe('a-b_c.d!e*f(g)h');
  });

  it('escapes reserved URL characters', () => {
    expect(ecpayUrlEncode('a & b=c')).toBe('a%20%26%20b%3Dc');
    expect(ecpayUrlEncode('100%')).toBe('100%25');
  });

  it('equals encodeURIComponent on real inputs (substitutions are no-ops on JS output)', () => {
    // `encodeURIComponent` never emits %2d/%5f/%2e/%21/%2a/%28/%29, so for any
    // real input the result must equal plain `encodeURIComponent` — matching
    // ECPay's canonical JS reference implementation.
    for (const input of ['a-b_c.d!e*f(g)h', 'Keigo & Business (100%)', 'https://x.io/cb?a=1&b=2']) {
      expect(ecpayUrlEncode(input)).toBe(encodeURIComponent(input));
    }
  });
});

describe('applyEcpayEncodeSubstitutions (§5 documented substitution table)', () => {
  it('maps the .NET-style escapes to the safe characters', () => {
    expect(applyEcpayEncodeSubstitutions('%2d%5f%2e%21%2a%28%29')).toBe('-_.!*()');
  });

  it('leaves lower and upper hex forms both normalized', () => {
    expect(applyEcpayEncodeSubstitutions('%2D %2d')).toBe('- -');
  });

  it('leaves unrelated escapes untouched', () => {
    expect(applyEcpayEncodeSubstitutions('%20%26%3D')).toBe('%20%26%3D');
  });
});

describe('canonicalCheckMacString (pipeline golden)', () => {
  it('produces the documented HashKey/HashIV + lowercase + urlencoded string', async () => {
    await expect(canonicalCheckMacString(V1_PARAMS, HASH_KEY, HASH_IV)).resolves.toBe(
      'hashkey%3d5294y06jbispm5x9%26choosepayment%3dcredit%26encrypttype%3d1' +
        '%26itemname%3dkeigo%20essentials%26language%3djpn%26merchantid%3d2000132' +
        '%26merchanttradedate%3d2026%2f08%2f16%2010%3a30%3a00' +
        '%26merchanttradeno%3dbjh202608160001%26needextrapaidinfo%3dn' +
        '%26paymenttype%3daio%26returnurl%3dhttps%3a%2f%2fexample.com%2ffunctions%2fv1' +
        '%2fecpay-callback%26totalamount%3d790' +
        '%26tradedesc%3dbusiness%20japanese%20hub%20book%20purchase' +
        '%26hashiv%3dv77hokgq4kwxnnis',
    );
  });
});

describe('verifyCheckMac', () => {
  it('accepts a correct expected value', async () => {
    await expect(verifyCheckMac(V1_PARAMS, HASH_KEY, HASH_IV, V1_EXPECTED)).resolves.toBe(true);
  });

  it('is case-insensitive', async () => {
    await expect(verifyCheckMac(V1_PARAMS, HASH_KEY, HASH_IV, V1_EXPECTED.toLowerCase())).resolves.toBe(true);
  });

  it('rejects a wrong expected value', async () => {
    await expect(verifyCheckMac(V1_PARAMS, HASH_KEY, HASH_IV, V2_EXPECTED)).resolves.toBe(false);
  });

  it('rejects missing / empty expected values', async () => {
    await expect(verifyCheckMac(V1_PARAMS, HASH_KEY, HASH_IV, undefined)).resolves.toBe(false);
    await expect(verifyCheckMac(V1_PARAMS, HASH_KEY, HASH_IV, '')).resolves.toBe(false);
  });
});

describe('sha256Hex', () => {
  it('computes the known SHA-256 of "hello"', async () => {
    await expect(sha256Hex('hello')).resolves.toBe(
      '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824',
    );
  });
});
